import type { CommissionProductModel, CommissionsViewModel } from "../models/site";

const shared = {
  descriptionClassName: "phone-case-description",
  swatchesClassName: "phone-case-swatches",
  detailsClassName: "phone-case-details",
  galleryAlt: () => "",
};

export function getCommissionsViewModel(): CommissionsViewModel {
  const products: CommissionProductModel[] = [
    {
      ...shared,
      id: "phone-case",
      title: "Phone Case",
      layout: "visual-left",
      sectionClassName: "phone-case-product",
      contentClassName: "phone-case-content",
      mainImage: "/phone-case-art.png",
      mainImageAlt: "Custom floral phone case",
      secondaryImage: "/phone-case-yellow.png",
      toneClassName: "phone-case-tone-card",
    },
    {
      ...shared,
      id: "tote-bag",
      title: "Tote Bag",
      layout: "visual-right",
      sectionClassName: "tote-bag-product",
      contentClassName: "tote-bag-content",
      descriptionClassName: "tote-bag-description",
      swatchesClassName: "tote-bag-swatches",
      detailsClassName: "tote-bag-details",
      mainImage: "/tote-bag-art.png",
      mainImageAlt: "Natural canvas tote bag",
      secondaryImage: "/tote-bag-neutral.png",
      toneClassName: "tote-bag-tone-card",
    },
    {
      ...shared,
      id: "travel-tumbler",
      title: "Travel Tumbler",
      layout: "visual-left",
      sectionClassName: "phone-case-product travel-tumbler-product",
      contentClassName: "phone-case-content",
      mainImage: "/travel-tumbler-art.png",
      mainImageAlt: "Natural travel tumbler",
      secondaryImage: "/travel-tumbler-neutral.png",
      toneClassName: "phone-case-tone-card",
    },
    {
      ...shared,
      id: "tshirt",
      title: "T-shirt",
      layout: "gallery-right",
      sectionClassName: "tshirt-product",
      contentClassName: "tote-bag-content tshirt-content",
      descriptionClassName: "tote-bag-description",
      swatchesClassName: "tote-bag-swatches",
      detailsClassName: "tote-bag-details",
      galleryClassName: "tshirt-gallery",
      galleryImages: [1, 2, 3, 4].map((n) => `/tshirt-product-${n}.png`),
      galleryAlt: (index) => `Custom printed T-shirt example ${index + 1}`,
    },
    {
      ...shared,
      id: "linen-journal",
      title: "Linen Journal",
      layout: "gallery-left",
      sectionClassName: "linen-journal-product",
      contentClassName: "phone-case-content linen-journal-content",
      galleryClassName: "linen-journal-gallery",
      galleryImages: [1, 2, 3, 4].map((n) => `/linen-journal-${n}.png`),
      galleryAlt: (index) => (index === 0 ? "Natural linen journal" : "Linen journal colour option"),
    },
    {
      ...shared,
      id: "special-card",
      title: "Special Card",
      layout: "gallery-left",
      sectionClassName: "linen-journal-product special-card-product",
      contentClassName: "phone-case-content linen-journal-content",
      galleryClassName: "linen-journal-gallery",
      galleryImages: [1, 2, 3, 4].map((n) => `/special-card-${n}.png`),
      galleryAlt: (index) => (index === 0 ? "Custom birthday special card" : "Special card colour option"),
    },
    {
      ...shared,
      id: "postcard",
      title: "Post Card",
      layout: "gallery-right",
      sectionClassName: "tshirt-product postcard-product",
      contentClassName: "tote-bag-content tshirt-content",
      descriptionClassName: "tote-bag-description",
      swatchesClassName: "tote-bag-swatches",
      detailsClassName: "tote-bag-details",
      galleryClassName: "tshirt-gallery",
      galleryImages: [1, 2, 3, 4].map((n) => `/postcard-product-${n}.png`),
      galleryAlt: (index) => (index === 0 ? "Custom printed postcard" : "Postcard colour option"),
    },
    {
      ...shared,
      id: "canvas-prints",
      title: "Canvas Prints",
      layout: "gallery-right",
      sectionClassName: "tshirt-product canvas-prints-product",
      contentClassName: "tote-bag-content tshirt-content",
      descriptionClassName: "tote-bag-description",
      swatchesClassName: "tote-bag-swatches",
      detailsClassName: "tote-bag-details",
      galleryClassName: "canvas-prints-gallery",
      toneClassName: "canvas-prints-tone-card",
      galleryImages: ["/canvas-prints-1.png", "", ""],
      galleryAlt: (index) => (index === 0 ? "Custom canvas print displayed on a brick wall" : ""),
    },
  ];

  return {
    categories: [
      "TRAVEL TUMBLER",
    "POSTCARD",
    "SPECIAL CARD",
    "CANVAS PRINTS",
      "PHONE CASE",
      "LINEN JOURNAL",
      "T-SHIRT",
      "TOTE BAG",
    ],
    products,
  };
}
